/*
   Copyright 2011  U.S. Centers for Disease Control and Prevention

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package gov.cdc.phix.connector.mirthclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 * Generated with JBoss wsconsume
 * @version $Id: //PHLISSA_HUB/PHIXConnectorService/src/gov/cdc/phix/connector/mirthclient/DefaultAcceptMessage.java#2 $ 
 */
@WebService(name = "DefaultAcceptMessage", targetNamespace = "http://ws.connectors.connect.mirth.com/")
public interface DefaultAcceptMessage {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "acceptMessage", targetNamespace = "http://ws.connectors.connect.mirth.com/", className = "gov.cdc.phix.connector.mirthclient.AcceptMessage")
    @ResponseWrapper(localName = "acceptMessageResponse", targetNamespace = "http://ws.connectors.connect.mirth.com/", className = "gov.cdc.phix.connector.mirthclient.AcceptMessageResponse")
    public String acceptMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
