/*
   Copyright 2011  U.S. Centers for Disease Control and Prevention

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package gov.cdc.phix.connector.mirthclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 * Generated with JBoss wsconsume
 * @version $Id: //PHLISSA_HUB/PHIXConnectorService/src/gov/cdc/phix/connector/mirthclient/DefaultAcceptMessageService.java#2 $ 
 */
@WebServiceClient(name = "DefaultAcceptMessageService", targetNamespace = "http://ws.connectors.connect.mirth.com/", wsdlLocation = "http://localhost:8081/services/Mirth?wsdl")
public class DefaultAcceptMessageService
    extends Service
{

    private final static URL DEFAULTACCEPTMESSAGESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gov.cdc.phix.connector.mirthclient.DefaultAcceptMessageService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gov.cdc.phix.connector.mirthclient.DefaultAcceptMessageService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/services/Mirth?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/services/Mirth?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DEFAULTACCEPTMESSAGESERVICE_WSDL_LOCATION = url;
    }

    public DefaultAcceptMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DefaultAcceptMessageService() {
        super(DEFAULTACCEPTMESSAGESERVICE_WSDL_LOCATION, new QName("http://ws.connectors.connect.mirth.com/", "DefaultAcceptMessageService"));
    }

    /**
     * 
     * @return
     *     returns DefaultAcceptMessage
     */
    @WebEndpoint(name = "DefaultAcceptMessagePort")
    public DefaultAcceptMessage getDefaultAcceptMessagePort() {
        return super.getPort(new QName("http://ws.connectors.connect.mirth.com/", "DefaultAcceptMessagePort"), DefaultAcceptMessage.class);
    }

}
